<?xml version="1.0" encoding="utf-8"?><Database Name="DsdaIntegrationRO" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=EPREVOREDO\SQLDEV2008R2A;Initial Catalog=DsdaIntegrationRO;User ID=sa;MultipleActiveResultSets=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DsdaIntegrationROConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblUploadSessions" Member="tblUploadSessions">
    <Type Name="tblUploadSession">
      <Column Name="UploadSessionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TotalFilesCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UploadedFilesCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MovedFilesCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedFilesCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DealerId" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>