<?xml version="1.0" encoding="utf-8"?><Database Name="DsdaIntegration" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local)\SQLDEV2017;Initial Catalog=DsdaIntegration;User ID=sa" SettingsObjectName="Dsda.DataAccess.Properties.Settings" SettingsPropertyName="DsdaIntegrationConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblUploadSessionDetails" Member="tblUploadSessionDetails">
    <Type Name="tblUploadSessionDetail">
      <Column Name="UploadSessionDetailId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UploadSessionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MessageType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblUploadSessions" Member="tblUploadSessions">
    <Type Name="tblUploadSession">
      <Column Name="UploadSessionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TotalFilesCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UploadedFilesCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MovedFilesCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedFilesCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DealerId" Type="System.String" DbType="nvarchar(10) NULL" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="nvarchar(max) NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblDocumentProcessing" Member="tblDocumentProcessings">
    <Type Name="tblDocumentProcessing">
      <Column Name="DocumentProcessingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UploadSessionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProcessingDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SourceDir" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="DealerId" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ContractDate" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CustNo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Stock" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Vin" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DealId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CabId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DocDate" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DocType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DocFolder" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsProcessed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProcessedErrors" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TagNames" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="OpenDate" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CloseDate" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Name1" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="VehID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>